apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  template:
    metadata:
      labels:
        riskstream.io/local-dev-minio: managed
    spec:
      containers:
      - name: minio
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  resources:
    requests:
      storage: 5Gi
