apiVersion: apps/v1
kind: Deployment
metadata:
  name: riskstream
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: riskstream
  template:
    metadata:
      labels:
        app: riskstream-api
        app.kubernetes.io/name: riskstream
    spec:
      containers:
        - name: riskstream
          image: ghcr.io/itsbriany/riskstream:main
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: ENVIRONMENT
              value: "production"
            - name: S3_ENDPOINT
              value: "minio:9000"
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: root-user
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: root-password
            - name: S3_USE_SSL
              value: "false"
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
